global:
  bin_path: "../build/tools/displayPTS2"
  input_root: "./results"
  output_root: "./screenshots"
  camera_dir: "../eval/cameras"

jobs:
  - name: "indoors/estimations"
    input_subdir: "indoors/estimation"
    
    pattern: "*/*.pts"
    
    is_error: false
    vector_as_color: true
    bounds: [-10.0, 10.0]
    properties: ["kMean", "Normal"]
    cameras: ["auto"]

  - name: "indoors/errors"
    input_subdir: "indoors/error"
    pattern: "*/*.pts"
    vector_as_color: true
    is_error: true
    bounds: [0, 10]
    # colorbar: true
    properties: ["Normal"]
    cameras: ["auto"]

