global:
  dataset_dir: "../datasets"
  output_dir: "./results"
  build_dir: "../build/estimators"
  
  save: ["stats", "estimation", "error"]

datasets:
  - name: "pipes"
    dir: "dataset_outdoor"
    extension: ".ply"
    pattern: ["Area_1_Site_1", "Area_1_Site_2_part_1"]
    
jobs:
  
  - name: "outdoors/pipes"
    executable: "compute_ponca_estimators"
    
    static_args:
      --stats: ""
      # --unsigned-curvature: ""
      --seed: 1
      # --abs: ""            # absolute error  if needed
    
    grid:
      -e: ["3DQuadric", "PC-MLS", "2-Monge", "Varifolds","VarifoldsMeanPlane", "WaveJets", "AvgHexagram", "ShapeOperator", "PCA", "ASO", "APSS", "Sphere", "UnorientedSphere", "Cov2D", "NormCov2D", "NormCov3D", "Mean"]
      -r: [0.1]
      --mls-iter: [1]
      --kernel: ["smooth"]

  - name: "outdoors/pipes"
    executable: "compute_jetfitting"
    method_label: "JetFitting"

    static_args:
      --stats: ""
      --seed: 1
      # --abs: ""

    grid:
      -r: [0.1]
